### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by cxplay** [1357310795/QrCodeScanner#1]
1. 增加截取屏幕快捷键 (部分二维码显示会在鼠标点击移动或者窗口切换后消失)
2. 区域截取屏幕内容自动识别
3. 打开本地图片识别
4. 截取识别后自动复制内容到剪贴板(集合条目2减少显示主程序)

**Comment by 1357310795** [comment]
(1.01版本)[https://github.com/1357310795/QrCodeScanner/tree/1.01]
基本搞好了，还差个常驻后台。
减少显示主程序不太行，在极端情况下一张图会包含好几个二维码，自动扫描只能识别一个，要识别另外几个还要返回手动框选才行。
