### ISSUE TITLE
建议增加一个选项：使其能自动添加回车

### ISSUE THREAD

**Issue by shishirong** [1357310795/QrCodeScanner#14]
比如在物料批量扫码出入库登记的时候，只需要连续扫描就行，不用频繁地操作键盘鼠标摄像头来回切换。

**Comment by 1357310795** [comment]
感谢建议，下一个版本将把同类软件的这些功能全部吸收进来（

**Comment by 1517431720** [comment]
啥时候增加回车功能就好了 哈哈哈！

**Comment by 1357310795** [comment]
https://github.com/1357310795/QrCodeScanner/releases/tag/1.5

![image](https://github.com/1357310795/QrCodeScanner/assets/35869804/6de28490-c295-45a0-bd0c-a9b9ec873974)
