### ISSUE TITLE
扫描枪模式希望增加一个回车

### ISSUE THREAD

**Issue by 1517431720** [1357310795/QrCodeScanner#25]
在实际应用场景 用扫描枪模式缺少回车 太痛苦了 我想弄一个工业摄像头+自动启停流水线 自动识别条码模拟键盘输出 减少人工扫描的项目 但是目前缺少个回车功能 希望大佬赶快增加 嘻嘻嘻！

**Comment by 1357310795** [comment]
之前一直没空，预计近期会增加这个功能

**Comment by 1357310795** [comment]
https://github.com/1357310795/QrCodeScanner/releases/tag/1.5

![image](https://github.com/1357310795/QrCodeScanner/assets/35869804/6de28490-c295-45a0-bd0c-a9b9ec873974)
