### ISSUE TITLE
希望增加集成库

### ISSUE THREAD

**Issue by TaffyStudio** [1357310795/QrCodeScanner#28]
作者大大方便建个项目只保留扫描核心功能(MyScanner.cs)作为库给其他C#项目调用吗
微信OpenCV识别二位码似乎对于腾讯系圆形二位码与ai二位码的识别效果更好 
不知道怎么单独把opencv拿出来

**Comment by TaffyStudio** [comment]
特殊二位码识别情况：
黑白普通二位码(对比度大)：均可正常识别

彩色普通二位码(对比度较小)：
![post](https://github.com/1357310795/QrCodeScanner/assets/25921583/1475891f-318f-4183-9b3e-82998ff9a0f1)
Zbar无法识别频道码(圆形),opencv均正常识别，ZXing无法识别

新版QQ个人圆形二位码：
![54b674f8ba90594d5af0b64cd0e28a1e](https://github.com/1357310795/QrCodeScanner/assets/25921583/5090c87d-9fd7-4cac-b5dd-3fd9380461b5)
Zbar小概率手动框选可识别,opencv正常识别,ZXing无法识别

新版QQ个人AI二位码：
![b88a4f51842e891f2d7ed85da6dc7f68](https://github.com/1357310795/QrCodeScanner/assets/25921583/3f497531-b6e3-428e-a315-19d6189085fb)
opencv小概率手动框选可识别,Zbar,ZXing无法识别

旧版QQ频道圆形二位码(高对比度)：
![qq_guild_qrcode1678460075725-768x1365](https://github.com/1357310795/QrCodeScanner/assets/25921583/ce088fef-2ea9-46f4-84f1-ee2bd910df5e)
均可正常识别

新版QQ频道圆形二位码(低对比度)：
![ebc2601ad5f1c10a816132c861594892](https://github.com/1357310795/QrCodeScanner/assets/25921583/2949c7be-d9ca-45ea-b9be-6f17550cbe06)
Zbar,opencv正常识别,ZXing无法识别

**Comment by 1357310795** [comment]
> 不知道怎么单独把opencv拿出来

如果不嫌opencv大（100+MB），直接装上opencvsharp的nuget就能用了

前几天写了一篇文章来讲精简这件事

https://zhuanlan.zhihu.com/p/679705899

我自己用的是这个库

https://www.nuget.org/packages/Teru.Code.WechatQrcode.Lite/

你可以直接用，参考 MyScanner.cs 的代码

**Comment by 1357310795** [comment]
当时就是因为AI艺术二维码，只有微信扫得出，ZXing/Zbar死活不行，所以才想到集成opencv

**Comment by TaffyStudio** [comment]
> > 不知道怎么单独把opencv拿出来
> 
> 如果不嫌opencv大（100+MB），直接装上opencvsharp的nuget就能用了 

抛出异常 DllNotFoundException: 无法加载 DLL“OpenCvSharpExtern”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
![image](https://github.com/1357310795/QrCodeScanner/assets/25921583/cbd1cea5-64ed-4542-90ef-7de8fc4033f9)

OpenCvSharp4.runtime.win
OpenCvSharp4
Teru.Code.WechatQrcode.Lite
都安上也不不行

**Comment by TaffyStudio** [comment]
甚至直接把MyQrCodeScanner生成的全部dll复制过去也不行

**Comment by TaffyStudio** [comment]
ASP.NET WebApi2 用不了这个吗

**Comment by TaffyStudio** [comment]
把OpenCvSharpExtern放system32里倒是好使了
还得把几个path改成System.Web.HttpContext.Current.Server.MapPath

**Comment by TaffyStudio** [comment]
解决了 WebApi2 工作目录不是网站根目录 是C:\Program Files\IIS Express 把dll复制到这就解决了
