### ISSUE TITLE
开发大大你好 这个扫描枪模式 扫描成功后 不能播放提示音

### ISSUE THREAD

**Issue by bitbangonline** [1357310795/QrCodeScanner#3]
![image](https://user-images.githubusercontent.com/71771386/134839391-92b3aafe-4bc2-4ed1-b96c-8f9cf313e22f.png)

**Comment by bitbangonline** [comment]
可以确定已经扫描成功了 但没有声音😂

**Comment by 1357310795** [comment]
这个音频文件方便上传一下吗？我复现一下

**Comment by 1357310795** [comment]
你的这个提示音是从站长素材下载的吗？我找到了同名文件，经测试没有问题🙄

**Comment by bitbangonline** [comment]
> 你的这个提示音是从站长素材下载的吗？我找到了同名文件，经测试没有问题🙄

抱歉 我没有及时看到消息😂 确实是从站长素材下载的 您的水平真高 我不知道我问题出在了哪里 我扫描成功之后 总是默默的复制到我的剪切板 并没有发出声音提示我  我不知道我问题出在哪里ʘᴗʘʘᴗʘ

**Comment by bitbangonline** [comment]
> 你的这个提示音是从站长素材下载的吗？我找到了同名文件，经测试没有问题🙄

还有我想向您请教一个经验 您是怎么凭借是一串数字 和一个扩展名就定位到我是在哪里找的文件呢？太厉害了叭

**Comment by bitbangonline** [comment]
并且我可以确认所有音量开关都打开了

**Comment by 1357310795** [comment]
> > 你的这个提示音是从站长素材下载的吗？我找到了同名文件，经测试没有问题🙄
> 
> 还有我想向您请教一个经验 您是怎么凭借是一串数字 和一个扩展名就定位到我是在哪里找的文件呢？太厉害了叭

因为百度搜“音效”第一就是站长素材，我也经常用的，所以知道命名规则😁

**Comment by 1357310795** [comment]
> 并且我可以确认所有音量开关都打开了

试试下面的步骤：
1.重新下载这个文件。
2.打开“音量合成器”，看看是否程序是否被静音，以及是否有声音输出（中间灰色条是否跳动）
3.如果没输出，换另外的音频试试

**Comment by bitbangonline** [comment]
> > 并且我可以确认所有音量开关都打开了
> 
> 试试下面的步骤： 1.重新下载这个文件。 2.打开“音量合成器”，看看程序是否被静音，以及是否有声音输出（中间灰色条是否跳动） 3.如果没输出，换另外的音频试试


开发大大厉害 果然奏效啦
话说可以增加一个文本生成二维码的功能吗

**Comment by 1357310795** [comment]
生成二维码软件真的太多了，我懒得重复造轮子

**Comment by bitbangonline** [comment]
> 生成二维码软件真的太多了，我懒得重复造轮子

要是能集中到您这一个就好了😂
