### ISSUE TITLE
兼容BUG：无法使用摄像头

### ISSUE THREAD

**Issue by IFFCheckPass** [1357310795/QrCodeScanner#33]
https://github.com/1357310795/QrCodeScanner/assets/175326129/f5fbf6cb-80a5-4c32-bb36-a5c2d209418f

软件无法使用罗技C310摄像头，呈现白屏，Windows自带相机正常
其他usb2.0摄像头均可正常使用

**Comment by 1357310795** [comment]
试试旧版本的呢

https://github.com/1357310795/QrCodeScanner/releases/tag/1.5

**Comment by IFFCheckPass** [comment]
> 试试旧版本的呢
> 
> https://github.com/1357310795/QrCodeScanner/releases/tag/1.5

可以了 谢谢
