### ISSUE TITLE
1.2版本开机启动按钮是灰色的，不能设置。对话框优化 等建议

### ISSUE THREAD

**Issue by zla5** [1357310795/QrCodeScanner#6]
1.2版本开机启动按钮是灰色的，不能设置。快捷键截取屏幕识别到条码能不能不要弹出对话框，我扫10个条码，出来10个对话框，关起来很麻烦。另外窗口关闭按钮能不能设置为最小化到托盘，不要占用任务栏。实在要关闭可以右击托盘图标退出。

**Comment by zla5** [comment]
如果能添加截图功能就好了，就不用登陆qq了，还能识别条码。

**Comment by 1357310795** [comment]
> 1.2版本开机启动按钮是灰色的，不能设置。

![QQ图片20220618211259](https://user-images.githubusercontent.com/35869804/174439295-1d6cbf4a-fdf6-4a64-9b9d-034466797a3d.png)

**Comment by 1357310795** [comment]
> 我扫10个条码，出来10个对话框

如果能一起扫，请合并扫描（正如readme.md中展示的那样）

如果不能，不弹出对话框，用户怎么知道有没有扫描成功？

**Comment by 1357310795** [comment]
> 另外窗口关闭按钮能不能设置为最小化到托盘，不要占用任务栏。实在要关闭可以右击托盘图标退出。

目前扫描枪的窗口是这个模式，主窗口我再考虑考虑

**Comment by 1357310795** [comment]
> 添加截图功能

是一个很好的思路！但是截图软件不好做啊，要处理多显示器、高DPI等各种问题，花费精力较大。后续可能会考虑

**Comment by zla5** [comment]
> > 我扫10个条码，出来10个对话框
> 
> 如果能一起扫，请合并扫描（正如readme.md中展示的那样）
> 
> 如果不能，不弹出对话框，用户怎么知道有没有扫描成功？

快捷键扫描不成功不是会弹出截图么提示没有找到么，或者你可以设置识别到的声音？

**Comment by zla5** [comment]
> > > 我扫10个条码，出来10个对话框
> > 
> > 
> > 如果能一起扫，请合并扫描（正如readme.md中展示的那样）
> > 如果不能，不弹出对话框，用户怎么知道有没有扫描成功？
> 
> 快捷键扫描不成功不是会弹出截图么提示没有找到么，或者你可以设置识别到的声音？

扫描到的结要填写到对应的地方，只能一个个去识别，一直弹出窗口，我要一个个去关闭，这真的很麻烦。

**Comment by 1357310795** [comment]
😂我好像明白了你的需求。这个让用户选择区域（就像QQ截屏那样）应该不复杂，有代码可以参考，我明天看看能不能改。

复制到剪切板，不弹出窗口也好办，加个选项就行。

**Comment by zla5** [comment]
> 复制到剪切板，不弹出窗口也好办，加个选项就行。

我就是说的这种全屏全局扫描识别，直接复制到剪切板，不显示窗口。你这个识别率很高，基本上不会出现识别不到的情况。所以也不需要像qq截屏那样还要鼠标去框一下。

**Comment by 1357310795** [comment]
https://github.com/1357310795/QrCodeScanner/releases/tag/1.3
应该全部解决了
