### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by ping9719** [1357310795/QrCodeScanner#8]
在不停的扫描本地图片和截图屏幕后，发现内存占用从200M升级到1.1G，应该是没有释放内存

**Comment by 1357310795** [comment]
感谢反馈！代码一年多前写的了，有些地方没考虑周全（其实是基本没有优化

有空会优化的！

**Comment by ping9719** [comment]
哈哈哈哈  不存在 小问题  只是我一不小心看到了

**Comment by 1357310795** [comment]
Bitmap调用Dispose并没有立刻释放内存，还是要等GC。GC目前来看并没有问题，就是阈值可能有点高。如有疑问，欢迎 Reopen。
