### ISSUE TITLE
Windows 7 x64截取屏幕功能无效

### ISSUE THREAD

**Issue by youngbais** [1357310795/QrCodeScanner#9]
Windows 7 x64截取屏幕功能点了以后没有任何反应，按截取快捷键也是一样的，是不支持Windows 7截取屏幕吗？

**Comment by 1357310795** [comment]
感谢反馈！开发的时候未测试win7兼容性。有空会修复的

**Comment by youngbais** [comment]
> 感谢反馈！开发的时候未测试win7兼容性。有空会修复的

好的，辛苦了，感谢开发这么实用的工具。

**Comment by youngbais** [comment]
> 感谢反馈！开发的时候未测试win7兼容性。有空会修复的

请问下1.4还是没有修复吗?截图功能点了还是没有任何反应.使用快捷键也是一样的情况.

**Comment by 1357310795** [comment]
感谢您对本项目的持续关注！之前把这事忘了，最近比较忙，预计两周内给出解决方案。

**Comment by youngbais** [comment]
> 感谢您对本项目的持续关注！之前把这事忘了，最近比较忙，预计两周内给出解决方案。

好的.感谢.

**Comment by 1357310795** [comment]
https://github.com/1357310795/QrCodeScanner/releases/tag/1.41

ok了，检查发现抄来的代码里用了 GetDpiForMonitor 函数，
> 最低受支持的客户端 | Windows 8.1 [仅限桌面应用]

Win7 时代甚至还没有为每个显示器设置不同 DPI 的功能哈哈
